language: rust
rust:
  - nightly
  - beta
  - stable
  
cache:
  cargo: true
  apt: true

matrix:
  allow_failures:
    - rust: nightly
    
env:
  global:
    # - RUSTFLAGS="-C link-dead-code"
    - OPENSSL_VERSION=openssl-1.0.2

before_install:
  - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl libssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev
